{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (include "orders-api.name" .) .Values.serviceAccount.name }}
  labels:
    {{- include "orders-api.labels" . | nindent 4 }}
{{- end }}
